"use client";

import {useCallback,useEffect,useRef,useState} from "react";
import Link from "next/link";
import AlgorithmWorkbench,{CalcGrid,Formula,HistoryScrubber,ParamList,ProcessFlow} from "./algorithm-workbench";
import {Localized} from "./language-provider";

type Boid={id:number;x:number;y:number;vx:number;vy:number};type Snap={tick:number;polarization:number;spacing:number;neighbors:number};type Vec={x:number;y:number};
const BW=800,BH=500,OBSTACLES=[{x:250,y:180,r:38},{x:540,y:330,r:48}];
const seeded=(seed:number)=>()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
const makeBoids=(n:number,random=Math.random)=>Array.from({length:n},(_,i)=>{const a=random()*Math.PI*2,s=1.4+random()*1.2;return{id:i,x:80+random()*(BW-160),y:60+random()*(BH-120),vx:Math.cos(a)*s,vy:Math.sin(a)*s}});
const norm=(x:number,y:number)=>{const d=Math.hypot(x,y)||1;return{x:x/d,y:y/d}};
function FlockChart({data}:{data:Snap[]}){const d=data.slice(-80),pts=d.map((v,i)=>`${i/Math.max(1,d.length-1)*100},${52-v.polarization*.48}`).join(" ");return <svg viewBox="0 0 100 56" preserveAspectRatio="none" className="ai-mini-chart flock-chart"><path d="M0 4H100M0 28H100M0 52H100"/><polyline points={pts}/></svg>}

export default function BoidsLab(){
  const[count,setCount]=useState(80),[separation,setSeparation]=useState(1.5),[alignment,setAlignment]=useState(1),[cohesion,setCohesion]=useState(.75),[radius,setRadius]=useState(70),[speed,setSpeed]=useState(2.6),[predatorOn,setPredatorOn]=useState(false),[predator,setPredator]=useState<Vec>({x:400,y:250}),[running,setRunning]=useState(true),[boids,setBoids]=useState<Boid[]>(()=>makeBoids(80,seeded(91))),[tick,setTick]=useState(0),[history,setHistory]=useState<Snap[]>([{tick:0,polarization:0,spacing:0,neighbors:0}]),[trace,setTrace]=useState({neighbors:0,separation:0,alignment:0,cohesion:0,avoidance:0}),[replayIndex,setReplayIndex]=useState(0);
  const boidsRef=useRef(boids),tickRef=useRef(tick);useEffect(()=>{boidsRef.current=boids},[boids]);useEffect(()=>{tickRef.current=tick},[tick]);
  const reset=(n=count)=>{const b=makeBoids(n);setRunning(false);setBoids(b);setTick(0);setHistory([{tick:0,polarization:0,spacing:0,neighbors:0}]);setReplayIndex(0);setTrace({neighbors:0,separation:0,alignment:0,cohesion:0,avoidance:0})};
  const step=useCallback(()=>{const current=boidsRef.current;let totalNeighbors=0,totalSpacing=0,forceS=0,forceA=0,forceC=0,forceO=0;const next=current.map(b=>{let sx=0,sy=0,ax=0,ay=0,cx=0,cy=0,n=0,spacing=0;for(const o of current){if(o.id===b.id)continue;let dx=o.x-b.x,dy=o.y-b.y;if(Math.abs(dx)>BW/2)dx-=Math.sign(dx)*BW;if(Math.abs(dy)>BH/2)dy-=Math.sign(dy)*BH;const d=Math.hypot(dx,dy);if(d<radius){n++;spacing+=d;ax+=o.vx;ay+=o.vy;cx+=dx;cy+=dy;if(d<radius*.38){sx-=dx/(d*d+.1);sy-=dy/(d*d+.1)}}}totalNeighbors+=n;if(n)totalSpacing+=spacing/n;let fx=sx*separation*18,fy=sy*separation*18;if(n){fx+=(ax/n-b.vx)*alignment*.045;fy+=(ay/n-b.vy)*alignment*.045;fx+=cx/n*cohesion*.0018;fy+=cy/n*cohesion*.0018}forceS+=Math.hypot(sx*separation*18,sy*separation*18);forceA+=n?Math.hypot((ax/n-b.vx)*alignment*.045,(ay/n-b.vy)*alignment*.045):0;forceC+=n?Math.hypot(cx/n*cohesion*.0018,cy/n*cohesion*.0018):0;
      for(const o of OBSTACLES){const dx=b.x-o.x,dy=b.y-o.y,d=Math.hypot(dx,dy);if(d<o.r+55){const q=(o.r+55-d)/(o.r+55);fx+=dx/(d||1)*q*.35;fy+=dy/(d||1)*q*.35;forceO+=q}}
      if(predatorOn){const dx=b.x-predator.x,dy=b.y-predator.y,d=Math.hypot(dx,dy);if(d<150){const q=(150-d)/150;fx+=dx/(d||1)*q*.8;fy+=dy/(d||1)*q*.8;forceO+=q}}
      let vx=b.vx+fx,vy=b.vy+fy;const dir=norm(vx,vy);vx=dir.x*speed;vy=dir.y*speed;return{...b,x:(b.x+vx+BW)%BW,y:(b.y+vy+BH)%BH,vx,vy}});const n=current.length,meanV=next.reduce((s,b)=>({x:s.x+b.vx/speed,y:s.y+b.vy/speed}),{x:0,y:0}),polarization=Math.hypot(meanV.x,meanV.y)/n,neighbors=totalNeighbors/n,spacing=totalSpacing/Math.max(1,next.filter((_,i)=>current.some(o=>o.id!==current[i].id)).length),nextTick=tickRef.current+1;setBoids(next);setTick(nextTick);setTrace({neighbors,separation:forceS/n,alignment:forceA/n,cohesion:forceC/n,avoidance:forceO/n});if(nextTick%10===0)setHistory(h=>{const ns=[...h,{tick:nextTick,polarization,spacing,neighbors}];setReplayIndex(ns.length-1);return ns})
  },[alignment,cohesion,predator,predatorOn,radius,separation,speed]);
  useEffect(()=>{if(!running)return;const t=window.setInterval(step,34);return()=>window.clearInterval(t)},[running,step]);
  const velocities=boids.map(b=>Math.hypot(b.vx,b.vy)),avgSpeed=velocities.reduce((a,b)=>a+b,0)/Math.max(1,boids.length),mean=boids.reduce((s,b)=>({x:s.x+b.vx/Math.max(.01,speed),y:s.y+b.vy/Math.max(.01,speed)}),{x:0,y:0}),polarization=Math.hypot(mean.x,mean.y)/Math.max(1,boids.length)*100,replay=history[Math.min(replayIndex,history.length-1)]??history[0];
  return <Localized><main className="viz-page ai-page boids-page"><header className="viz-nav"><Link href="/" className="exit-lab viz-exit"><span className="exit-symbol">←</span><span><b>退出实验</b><small>返回目录</small></span></Link><span>06 / EMERGENT SWARM INTELLIGENCE</span><Link href="/evolutionary-game" className="next-lab">回到第一个实验 →</Link></header>
    <section className="viz-intro"><div><p className="viz-kicker">Emergent behavior laboratory</p><h1>简单规则如何<br/>形成群体智能</h1></div><p>每个个体只观察附近邻居：保持距离、对齐方向、靠近群体。没有中央指挥，连贯的鸟群、分裂与绕障却会从局部规则中自然出现。</p></section>
    <section className="ai-workspace boids-workspace"><aside className="viz-controls"><div className="viz-panel-title">群体控制 <small>CONTROL</small></div><div className="viz-run"><button onClick={()=>setRunning(v=>!v)}>{running?"暂停群体":"启动群体"}</button><button onClick={step} aria-label="单步群体">+1</button><button onClick={()=>reset()} aria-label="重置群体">↻</button></div><BRange label="个体数量" value={count} min={20} max={160} step={10} display={`${count} 个`} onChange={v=>{setCount(v);reset(v)}}/><BRange label="分离权重" value={separation} min={0} max={3} step={.1} display={separation.toFixed(1)} onChange={setSeparation}/><BRange label="对齐权重" value={alignment} min={0} max={3} step={.1} display={alignment.toFixed(1)} onChange={setAlignment}/><BRange label="聚合权重" value={cohesion} min={0} max={3} step={.1} display={cohesion.toFixed(1)} onChange={setCohesion}/><BRange label="感知半径" value={radius} min={25} max={130} step={5} display={`${radius} px`} onChange={setRadius}/><BRange label="移动速度" value={speed} min={.8} max={5} step={.2} display={speed.toFixed(1)} onChange={setSpeed}/><button className={`predator-toggle ${predatorOn?"active":""}`} onClick={()=>setPredatorOn(v=>!v)}>{predatorOn?"关闭捕食者":"加入捕食者"}</button></aside>
      <section className="ai-stage"><div className="warehouse-head"><span>涌现行为场</span><div><i className={running?"on":""}/>{running?"RUNNING":"PAUSED"} · T{tick}</div></div><svg viewBox={`0 0 ${BW} ${BH}`} className="boids-map" aria-label="Boids群体行为场" onClick={e=>{if(!predatorOn)return;const r=e.currentTarget.getBoundingClientRect();setPredator({x:(e.clientX-r.left)/r.width*BW,y:(e.clientY-r.top)/r.height*BH})}}><rect width={BW} height={BH} className="boids-floor"/><g className="boid-grid">{Array.from({length:9},(_,i)=><path key={i} d={`M${i*100} 0V500M0 ${i*62.5}H800`}/>)}</g>{OBSTACLES.map((o,i)=><g key={i} className="boid-obstacle"><circle cx={o.x} cy={o.y} r={o.r}/><circle cx={o.x} cy={o.y} r={o.r+45}/></g>)}{predatorOn&&<g className="predator" transform={`translate(${predator.x} ${predator.y})`}><circle r="14"/><circle r="145"/><path d="M-8 -5L10 0-8 5Z"/></g>}{boids.map((b,i)=><g className="boid" key={b.id} transform={`translate(${b.x} ${b.y}) rotate(${Math.atan2(b.vy,b.vx)*180/Math.PI})`}><path d="M9 0L-7 5L-3 0L-7-5Z" fill={i%5===0?"#d3a14f":"#3f8068"}/>{i===0&&<circle r={radius} className="sense-ring"/>}</g>)}</svg><div className="ai-legend"><span><i className="boid-swatch"/>个体</span><span><i className="sense-swatch"/>R1 的感知半径</span><span>点击场地可移动捕食者</span></div></section>
      <aside className="ai-stats"><div className="viz-panel-title">群体状态 <small>LIVE METRICS</small></div><div className="ai-kpis"><div><span>方向一致度</span><b>{polarization.toFixed(0)}%</b></div><div><span>平均邻居数</span><b>{trace.neighbors.toFixed(1)}</b></div><div><span>平均速度</span><b>{avgSpeed.toFixed(1)}</b></div><div><span>当前个体</span><b>{boids.length}</b></div></div><div className="ai-chart"><span>方向一致度变化</span><FlockChart data={history}/></div><div className="force-stack"><span>本步平均规则强度</span>{[["分离",trace.separation,"#bd5b4c"],["对齐",trace.alignment,"#577c9a"],["聚合",trace.cohesion,"#3f8068"],["避障",trace.avoidance,"#d3a14f"]].map(([n,v,c])=><div key={String(n)}><b>{n}</b><i><em style={{width:`${Math.min(100,Number(v)*180)}%`,background:String(c)}}/></i><small>{Number(v).toFixed(3)}</small></div>)}</div><p className="ai-note">黄色个体只用于增强空间辨识，遵循与绿色个体完全相同的规则。</p></aside></section>
    <AlgorithmWorkbench title="没有领导者，群体秩序从哪里产生" subtitle="每个个体只计算邻域中的三个向量，再与避障力合成下一帧速度。" tabs={[
      {id:"principle",label:"算法原理",content:<div className="workbench-split"><div><h3>每个个体的局部循环</h3><ProcessFlow steps={["寻找感知半径内邻居","远离过近个体","对齐邻居平均速度","靠近邻居几何中心","合成向量并限制速度"]}/></div><div><h3>局部规则的合成</h3><Formula note="三个权重决定鸟群更重视安全距离、方向一致还是群体聚集。">a = wₛS + wₐA + w꜀C + O</Formula><Formula note="所有个体并行执行同一套规则，没有中央规划器。">v(t+1) = limit(v(t) + a)</Formula></div></div>},
      {id:"step",label:"本步计算",content:<CalcGrid items={[{label:"平均邻居数",value:trace.neighbors.toFixed(1)},{label:"分离力",value:trace.separation.toFixed(3)},{label:"对齐力",value:trace.alignment.toFixed(3)},{label:"聚合力",value:trace.cohesion.toFixed(3)},{label:"避障/逃逸力",value:trace.avoidance.toFixed(3)}]}/>},
      {id:"history",label:"历史回放",content:<HistoryScrubber value={replayIndex} max={history.length-1} onChange={setReplayIndex} label={`TICK ${replay.tick}`}><CalcGrid items={[{label:"方向一致度",value:`${(replay.polarization*100).toFixed(1)}%`},{label:"平均间距",value:replay.spacing.toFixed(1)},{label:"平均邻居",value:replay.neighbors.toFixed(1)}]}/></HistoryScrubber>},
      {id:"parameters",label:"参数解释",content:<ParamList items={[{symbol:"wₛ",name:"分离权重",effect:"增强短距离排斥，防止个体重叠；过高会让群体变得松散。"},{symbol:"wₐ",name:"对齐权重",effect:"让个体靠近邻居平均方向，是形成同向运动的关键。"},{symbol:"w꜀",name:"聚合权重",effect:"把个体拉向邻居中心；过高可能形成拥挤团块。"},{symbol:"R",name:"感知半径",effect:"决定局部信息范围。太小难以形成整体秩序，太大则趋向全局同步。"},{symbol:"O",name:"避障与捕食者",effect:"额外的排斥向量会暂时撕裂鸟群，随后局部规则让它重新聚合。"}]}/>} ]}/>
  </main></Localized>
}
function BRange({label,value,min,max,step,display,onChange}:{label:string;value:number;min:number;max:number;step:number;display:string;onChange:(n:number)=>void}){return <div className="viz-control"><label>{label}<b>{display}</b></label><input aria-label={label} type="range" value={value} min={min} max={max} step={step} onChange={e=>onChange(+e.target.value)}/><small><span>{min}</span><span>{max}</span></small></div>}
