"use client";

import {useCallback,useEffect,useRef,useState} from "react";
import Link from "next/link";
import AlgorithmWorkbench,{CalcGrid,Formula,HistoryScrubber,ParamList,ProcessFlow} from "./algorithm-workbench";
import {Localized} from "./language-provider";

type Pos={x:number;y:number};type Snap={episode:number;reward:number;steps:number;epsilon:number};
const W=8,H=6,ACTIONS=[{dx:0,dy:-1,icon:"↑"},{dx:1,dy:0,icon:"→"},{dx:0,dy:1,icon:"↓"},{dx:-1,dy:0,icon:"←"}];
const WALLS=new Set(["2,0","2,1","2,2","4,2","5,2","6,2","4,3","1,4","2,4","4,4"]),START={x:0,y:5},GOAL={x:7,y:0},TRAPS=new Set(["6,4","3,1"]),key=(p:Pos)=>`${p.x},${p.y}`,index=(p:Pos)=>p.y*W+p.x;
const initialQ=()=>Array.from({length:W*H},()=>[0,0,0,0]);
function ReturnChart({data}:{data:Snap[]}){const d=data.slice(-60),vals=d.map(x=>x.reward),lo=Math.min(-5,...vals),hi=Math.max(5,...vals),pts=vals.map((v,i)=>`${i/Math.max(1,vals.length-1)*100},${52-(v-lo)/(hi-lo)*48}`).join(" ");return <svg viewBox="0 0 100 56" preserveAspectRatio="none" className="ai-mini-chart reward-chart"><path d="M0 4H100M0 28H100M0 52H100"/><polyline points={pts}/></svg>}

export default function QLearningLab(){
  const[alpha,setAlpha]=useState(.3),[gamma,setGamma]=useState(.92),[epsilon,setEpsilon]=useState(.28),[speed,setSpeed]=useState(180),[running,setRunning]=useState(false),[position,setPosition]=useState<Pos>(START),[episode,setEpisode]=useState(0),[totalSteps,setTotalSteps]=useState(0),[episodeSteps,setEpisodeSteps]=useState(0),[episodeReward,setEpisodeReward]=useState(0),[qValues,setQValues]=useState<number[][]>(initialQ),[history,setHistory]=useState<Snap[]>([{episode:0,reward:0,steps:0,epsilon:.28}]),[trace,setTrace]=useState({state:"START",action:"-",reward:0,oldQ:0,target:0,newQ:0,exploring:false}),[replayIndex,setReplayIndex]=useState(0);
  const qRef=useRef(initialQ()),posRef=useRef(position),epRef=useRef(episode),stepsRef=useRef(episodeSteps),rewardRef=useRef(episodeReward);useEffect(()=>{posRef.current=position},[position]);useEffect(()=>{epRef.current=episode},[episode]);useEffect(()=>{stepsRef.current=episodeSteps},[episodeSteps]);useEffect(()=>{rewardRef.current=episodeReward},[episodeReward]);
  const reset=()=>{const nextQ=initialQ();qRef.current=nextQ;setQValues(nextQ);setRunning(false);setPosition(START);setEpisode(0);setTotalSteps(0);setEpisodeSteps(0);setEpisodeReward(0);setHistory([{episode:0,reward:0,steps:0,epsilon}]);setReplayIndex(0);setTrace({state:"START",action:"-",reward:0,oldQ:0,target:0,newQ:0,exploring:false})};
  const step=useCallback(()=>{const p=posRef.current,state=index(p),exploring=Math.random()<epsilon;let action;if(exploring)action=Math.floor(Math.random()*4);else{const best=Math.max(...qRef.current[state]);const options=qRef.current[state].map((v,i)=>v===best?i:-1).filter(i=>i>=0);action=options[Math.floor(Math.random()*options.length)]}const move=ACTIONS[action];let next={x:p.x+move.dx,y:p.y+move.dy},reward=-.2;if(next.x<0||next.x>=W||next.y<0||next.y>=H||WALLS.has(key(next))){next=p;reward=-1}const terminal=key(next)===key(GOAL)||TRAPS.has(key(next));if(key(next)===key(GOAL))reward=20;else if(TRAPS.has(key(next)))reward=-15;const old=qRef.current[state][action],future=terminal?0:Math.max(...qRef.current[index(next)]),target=reward+gamma*future,newQ=old+alpha*(target-old);qRef.current[state][action]=newQ;setQValues(qRef.current.map(row=>[...row]));const newSteps=stepsRef.current+1,newReward=rewardRef.current+reward;setTotalSteps(v=>v+1);setTrace({state:`(${p.x},${p.y})`,action:ACTIONS[action].icon,reward,oldQ:old,target,newQ,exploring});
    if(terminal||newSteps>=120){const nextEp=epRef.current+1,snap={episode:nextEp,reward:newReward,steps:newSteps,epsilon};setEpisode(nextEp);setPosition(START);setEpisodeSteps(0);setEpisodeReward(0);setHistory(h=>{const n=[...h,snap];setReplayIndex(n.length-1);return n})}else{setPosition(next);setEpisodeSteps(newSteps);setEpisodeReward(newReward)}
  },[alpha,gamma,epsilon]);
  useEffect(()=>{if(!running)return;const t=window.setInterval(step,speed);return()=>window.clearInterval(t)},[running,speed,step]);
  const replay=history[Math.min(replayIndex,history.length-1)]??history[0],recent=history.slice(-20),successRate=recent.length>1?recent.filter(x=>x.reward>0).length/(recent.length-1)*100:0;
  return <Localized><main className="viz-page ai-page q-page"><header className="viz-nav"><Link href="/" className="exit-lab viz-exit"><span className="exit-symbol">←</span><span><b>退出实验</b><small>返回目录</small></span></Link><span>05 / REINFORCEMENT LEARNING</span><Link href="/boids" className="next-lab">下一个实验 →</Link></header>
    <section className="viz-intro"><div><p className="viz-kicker">Reinforcement learning laboratory</p><h1>智能体如何<br/>试错走出迷宫</h1></div><p>智能体没有地图答案，只能通过奖励和惩罚更新每个状态-动作的价值。探索会制造错误，利用则把已经学到的经验变成稳定路线。</p></section>
    <section className="ai-workspace"><aside className="viz-controls"><div className="viz-panel-title">学习控制 <small>CONTROL</small></div><div className="viz-run"><button onClick={()=>setRunning(v=>!v)}>{running?"暂停学习":"开始学习"}</button><button onClick={step} aria-label="单步学习">+1</button><button onClick={reset} aria-label="重置Q表">↻</button></div><QRange label="学习率 α" value={alpha} min={.05} max={.8} step={.05} display={alpha.toFixed(2)} onChange={setAlpha}/><QRange label="折扣因子 γ" value={gamma} min={.4} max={.99} step={.01} display={gamma.toFixed(2)} onChange={setGamma}/><QRange label="探索率 ε" value={epsilon} min={0} max={.8} step={.02} display={`${(epsilon*100).toFixed(0)}%`} onChange={setEpsilon}/><QRange label="运行速度" value={speed} min={40} max={700} step={20} display={`${(1000/speed).toFixed(1)} 步/秒`} onChange={setSpeed} reverse/><div className="q-rewards"><b>奖励规则</b><span><i className="goal-dot"/>终点 +20</span><span><i className="trap-dot"/>陷阱 −15</span><span><i className="wall-dot"/>撞墙 −1</span><span><i/>普通移动 −0.2</span></div></aside>
      <section className="ai-stage"><div className="warehouse-head"><span>Q 值迷宫</span><div><i className={running?"on":""}/>{running?"LEARNING":"PAUSED"} · EP {episode}</div></div><div className="q-grid">{Array.from({length:W*H},(_,i)=>{const x=i%W,y=Math.floor(i/W),p={x,y},wall=WALLS.has(key(p)),goal=key(p)===key(GOAL),trap=TRAPS.has(key(p)),vals=qValues[i],best=Math.max(...vals),bestA=vals.indexOf(best),intensity=Math.max(0,Math.min(1,(best+2)/15));return <div key={i} className={`q-cell ${wall?"wall":""} ${goal?"goal":""} ${trap?"trap":""}`} style={!wall&&!goal&&!trap?{background:`rgba(63,128,104,${.035+intensity*.32})`}:undefined}>{!wall&&<><span className="q-value">{best.toFixed(1)}</span>{best!==0&&<b className="q-arrow">{ACTIONS[bestA].icon}</b>}{key(position)===key(p)&&<i className="q-agent"/>}{goal&&<strong>GOAL</strong>}{trap&&<strong>−15</strong>}</>}</div>})}</div><div className="ai-legend"><span><i className="q-agent legend-agent"/>智能体</span><span>箭头 = 当前最佳动作</span><span>绿色越深 = 状态价值越高</span></div></section>
      <aside className="ai-stats"><div className="viz-panel-title">学习状态 <small>LIVE METRICS</small></div><div className="ai-kpis"><div><span>完成回合</span><b>{episode}</b></div><div><span>当前回报</span><b>{episodeReward.toFixed(1)}</b></div><div><span>当前步数</span><b>{episodeSteps}</b></div><div><span>近20轮成功率</span><b>{successRate.toFixed(0)}%</b></div></div><div className="ai-chart"><span>每回合累计回报</span><ReturnChart data={history}/></div><div className="q-live"><span>最近一次更新</span><b>{trace.state}　{trace.action}</b><p>{trace.exploring?"探索：随机选择动作":"利用：选择当前 Q 值最高的动作"}</p><small>Q: {trace.oldQ.toFixed(2)} → {trace.newQ.toFixed(2)}</small></div><p className="ai-note">累计执行 {totalSteps} 步。达到终点、掉入陷阱或超过 120 步后开始新回合。</p></aside></section>
    <AlgorithmWorkbench title="奖励如何变成一张可执行的策略表" subtitle="每走一步，智能体都用即时奖励和未来最大价值修正一个 Q 值。" accent="blue" tabs={[
      {id:"principle",label:"算法原理",content:<div className="workbench-split"><div><h3>一次状态转移</h3><ProcessFlow steps={["观察当前状态 s","探索或选择最佳动作 a","环境返回奖励 r","观察下一状态 s′","更新 Q(s,a)"]}/></div><div><h3>时序差分更新</h3><Formula note="目标值同时包含即时奖励和下一状态的最佳未来价值。">target = r + γ max Q(s′,a′)</Formula><Formula note="α 控制旧经验被新经验修正的幅度。">Q ← Q + α(target − Q)</Formula></div></div>},
      {id:"step",label:"本步计算",content:<><div className="step-callout"><span>STATE {trace.state}</span><b>动作 {trace.action} · 奖励 {trace.reward.toFixed(1)}</b><p>{trace.exploring?"本步来自随机探索。":"本步使用当前价值最高的动作。"}</p></div><CalcGrid items={[{label:"更新前 Q",value:trace.oldQ.toFixed(3)},{label:"TD 目标",value:trace.target.toFixed(3)},{label:"更新后 Q",value:trace.newQ.toFixed(3),tone:trace.newQ>trace.oldQ?"good":trace.newQ<trace.oldQ?"warn":undefined},{label:"当前回合",value:episode},{label:"回合内步数",value:episodeSteps}]}/></>},
      {id:"history",label:"历史回放",content:<HistoryScrubber value={replayIndex} max={history.length-1} onChange={setReplayIndex} label={`EPISODE ${replay.episode}`}><CalcGrid items={[{label:"回合总回报",value:replay.reward.toFixed(1),tone:replay.reward>0?"good":"warn"},{label:"完成步数",value:replay.steps},{label:"探索率",value:`${(replay.epsilon*100).toFixed(0)}%`} ]}/></HistoryScrubber>},
      {id:"parameters",label:"参数解释",content:<ParamList items={[{symbol:"α",name:"学习率",effect:"控制新经验覆盖旧 Q 值的速度；过高会使策略波动。"},{symbol:"γ",name:"折扣因子",effect:"越接近 1，越重视远期终点奖励；越低则更短视。"},{symbol:"ε",name:"探索率",effect:"按概率随机行动。为 0 时只利用现有经验，可能被错误策略锁死。"},{symbol:"r",name:"奖励设计",effect:"终点、陷阱、撞墙和移动成本共同塑造最终策略。"}]}/>} ]}/>
  </main></Localized>
}
function QRange({label,value,min,max,step,display,onChange,reverse=false}:{label:string;value:number;min:number;max:number;step:number;display:string;onChange:(n:number)=>void;reverse?:boolean}){return <div className="viz-control"><label>{label}<b>{display}</b></label><input aria-label={label} type="range" value={value} min={min} max={max} step={step} onChange={e=>onChange(+e.target.value)} style={reverse?{direction:"rtl"}:undefined}/><small><span>{min}</span><span>{max}</span></small></div>}
