"use client";

import {Children,cloneElement,createContext,isValidElement,ReactElement,ReactNode,useContext,useEffect,useMemo,useState} from "react";

export type Language="zh"|"en";

const dictionary:Record<string,string>={
  "个可交互":"interactive","算法实验":"algorithm labs","算法实验的信息流":"Information flow in an algorithm experiment","参数进入算法，改变内部状态，产生可观察结果，并通过反馈进入下一步计算。":"Parameters enter the algorithm, update its state, produce an observable outcome, and feed the next calculation.",
  "实验目录":"Experiment index","实验方法":"Method","进入实验":"Enter experiment","个可交互\n算法实验":"interactive\nalgorithm labs","看见算法，":"See algorithms, ","看见思考":"See thinking","拆开训练、搜索与协作过程。修改参数，查看每一步状态更新，再比较不同算法如何形成答案。":"Open up training, search, and coordination. Change parameters, inspect each update, and compare how algorithms form answers.","选择一个问题":"Choose a problem","进入实验目录":"Browse experiments","观察状态":"Observe state","改变参数":"Change parameters","单步验证":"Step through","比较结果":"Compare results","算法可视化":"Algorithm visualization","每个实验都能修改参数、逐步运行并回看关键状态。你看到的不只是答案，还有答案形成的过程。":"Change parameters, run step by step, and revisit key states. Inspect both the answer and the process that produced it.","实验中可观察":"Observable in the lab","用实践，":"Practice","理解算法":"Understand","建立基线":"Establish a baseline","先用默认参数运行，观察系统的自然状态。":"Start with default parameters and observe the system's baseline behavior.","单步观察":"Inspect one step","查看当前候选、计算结果以及算法为何接受这个决定。":"Inspect the candidate, the calculation, and why the algorithm accepts a decision.","控制变量":"Control variables","一次只改变一个条件，分离它对结果的真实影响。":"Change one condition at a time to isolate its effect.","回看转折":"Revisit turning points","拖动历史快照，对照关键变化发生前后的系统状态。":"Scrub through history and compare the states before and after a key change.","算法可视化实验室":"Algorithm Visualization Laboratory","演化、协作、优化与学习":"Evolution, coordination, optimization, and learning","返回实验目录 ↑":"Back to experiments ↑","算法运行结构":"Algorithm structure","一次实验中的信息流":"Information flow in one experiment","参数":"Parameters","状态更新":"State update","观察结果":"Outcome",
  "合作如何从背叛中演化？":"How can cooperation evolve from defection?","把囚徒困境放进一个会遗传、突变、出生和死亡的种群，观察策略竞争如何改变合作率与种群规模。":"Place the Prisoner's Dilemma inside an evolving population and observe how strategic competition changes cooperation and population size.","重复博弈":"Repeated game","遗传算法":"Genetic algorithm","逐代解析":"Generation analysis","5 类策略实时竞争":"Five strategy types compete live",
  "机器人怎样不堵车地搬完货？":"How can robots move cargo without gridlock?","在动态仓库中分配取货任务、规划最短路径并避免冲突，观察局部决策如何影响整个系统的吞吐量。":"Assign pickups, plan shortest paths, and resolve conflicts in a dynamic warehouse to see how local decisions shape throughput.","任务分配":"Task allocation","路径规划":"Path planning","逐步决策":"Stepwise decisions","8 台机器人协同调度":"Eight robots coordinate in real time",
  "一条路线如何逼近全局最优？":"How does a route approach the global optimum?","让不同搜索策略在同一组城市上竞争，逐步观察交叉、变异和局部改进怎样缩短旅行商回路。":"Compare search strategies on the same cities and inspect how crossover, mutation, and local improvement shorten the tour.","旅行商问题":"Traveling salesman","三种算法":"Three algorithms","候选解解析":"Candidate analysis","3 种搜索策略对比":"Compare three search strategies",
  "神经网络如何学会分类？":"How does a neural network learn classification?","从随机权重开始，观察前向传播、损失计算和反向传播怎样把模糊的预测区域塑造成决策边界。":"Start from random weights and watch forward passes, loss, and backpropagation shape a decision boundary.","神经网络":"Neural network","反向传播":"Backpropagation","决策边界":"Decision boundary","实时训练与边界演化":"Live training and boundary evolution",
  "智能体如何试错走出迷宫？":"How does an agent learn to escape a maze?","让智能体在奖励、陷阱和移动成本之间反复试错，观察一张空白 Q 表怎样逐渐变成稳定策略。":"Let an agent balance rewards, traps, and movement costs as an empty Q table becomes a stable policy.","探索与利用":"Explore vs. exploit","价值更新":"Value update","状态价值实时传播":"State values propagate live",
  "简单规则如何形成群体智能？":"How do simple rules create swarm intelligence?","每个个体只遵循分离、对齐和聚合三条局部规则，群体却会自行形成队列、绕障、分裂与重组。":"Each agent follows separation, alignment, and cohesion, yet the flock forms, avoids, splits, and regroups on its own.","涌现行为":"Emergent behavior","群体智能":"Swarm intelligence","160 个个体实时涌现":"160 agents produce live emergence",
  "退出实验":"Exit experiment","返回目录":"Back to index","下一个实验 →":"Next experiment →","回到第一个实验 →":"Back to first experiment →",
  "模拟器":"Simulator","模型说明":"Model","研究依据":"Research","实验控制":"Experiment controls","参数实时生效":"Changes apply live","初始种群":"Initial population","环境承载量 K":"Carrying capacity K","每次相遇轮数":"Rounds per encounter","选择压力 β":"Selection pressure β","基因突变率 μ":"Mutation rate μ","行动噪声 ε":"Action noise ε","情景预设":"Scenario presets","互惠占优":"Reciprocity wins","背叛入侵":"Defector invasion","高突变":"High mutation","高噪声":"High noise","囚徒困境收益":"Prisoner's Dilemma payoffs","收益矩阵":"Payoff matrix","合作，如何在背叛中":"How can cooperation","演化出来？":"evolve from defection?","每个圆点都是携带策略基因的个体。它们反复相遇、合作或背叛；收益决定谁更可能存活并留下后代，交叉与突变则不断制造新的行为。":"Each dot carries a strategy genome. Repeated cooperation and defection produce payoffs that shape survival and reproduction, while crossover and mutation create new behavior.","合作 / 合作":"Cooperate / cooperate","合作 / 背叛":"Cooperate / defect","背叛 / 合作":"Defect / cooperate","背叛 / 背叛":"Defect / defect","单步运行":"Run one generation","重置":"Reset",
  "多机器人":"Multi-robot","协作搬运":"coordination","中央调度器把等待货物分配给最近的空闲机器人。每台机器人独立规划最短路径，并在每一步通过预约下一格来避免碰撞。":"A central dispatcher assigns waiting cargo to the nearest idle robot. Each robot plans its own shortest path and reserves its next cell to avoid collisions.","调度器如何做出每一步决定":"How the dispatcher makes each decision","把任务分配、最短路搜索和冲突消解拆开观察；数据来自当前仓库的真实调度步。":"Inspect task allocation, shortest-path search, and conflict resolution using data from the live warehouse.",
  "旅行商问题":"Traveling salesman","路线优化":"route optimization","访问每座城市恰好一次并回到起点。城市数量稍一增加，可能路线就会爆炸式增长；搜索算法只能在巨大空间中不断逼近好答案。":"Visit every city exactly once and return to the start. As the route space explodes, search algorithms must approach good answers without exhaustive enumeration.","一条更短路线是怎样被找到的":"How a shorter route is found","每次迭代都公开候选路线、距离变化与接受条件；切换算法时，解释会同步变化。":"Every iteration exposes its candidate, distance change, and acceptance rule. The explanation updates when you switch algorithms.",
  "如何学会分类":"learns to classify","网络从随机权重开始。每轮训练都先预测，再沿误差反向计算梯度，让决策边界逐渐贴合你在画布上放置的数据。":"The network begins with random weights. Each epoch predicts, backpropagates the error, and reshapes the boundary around the data you place.","权重是怎样沿误差方向更新的":"How weights move against the error","观察一次完整的前向预测、损失计算、梯度回传与参数更新。":"Inspect a complete forward pass, loss calculation, gradient backpropagation, and parameter update.",
  "智能体如何":"How an agent","试错走出迷宫":"escapes by trial and error","智能体没有地图答案，只能通过奖励和惩罚更新每个状态-动作的价值。探索会制造错误，利用则把已经学到的经验变成稳定路线。":"The agent has no map. It updates state-action values from rewards and penalties, balancing exploratory mistakes with exploitation of learned routes.","奖励如何变成一张可执行的策略表":"How rewards become an executable policy","每走一步，智能体都用即时奖励和未来最大价值修正一个 Q 值。":"At every step, the agent corrects one Q value using immediate reward and the best estimated future value.",
  "简单规则如何":"How simple rules","形成群体智能":"create swarm intelligence","每个个体只观察附近邻居：保持距离、对齐方向、靠近群体。没有中央指挥，连贯的鸟群、分裂与绕障却会从局部规则中自然出现。":"Each agent sees only nearby neighbors, keeping distance, aligning direction, and moving toward the group. Flocking, splitting, and obstacle avoidance emerge without central control.","没有领导者，群体秩序从哪里产生":"Where flock order comes from without a leader","每个个体只计算邻域中的三个向量，再与避障力合成下一帧速度。":"Each agent computes three neighborhood vectors and combines them with obstacle avoidance to produce its next velocity.",
  "一代种群是怎样被计算出来的":"How one population generation is computed","从一组真实配对开始，追踪合作行为、平均收益、选择权重与下一代规模。":"Start from real pairings and trace cooperation, mean payoff, selection weights, and the size of the next generation.",
  "实验模式":"Experiment","教学模式":"Explainer","实验模式已启用":"Experiment mode enabled","模拟保持完整运行；切换到教学模式可查看公式、本步决策和历史快照。":"The simulation keeps running. Switch to Explainer to inspect formulas, decisions, and history.","展开算法解析 →":"Open explainer →",
  "算法原理":"Principle","本步计算":"Current step","本轮计算":"Current epoch","本代计算":"Current generation","历史回放":"History","参数解释":"Parameters","历史快照":"History snapshot","这里只回看记录，不会改变当前实验状态。":"This replays recorded states without changing the live experiment.",
  "调度控制":"Dispatch controls","训练控制":"Training controls","学习控制":"Learning controls","搜索控制":"Search controls","群体控制":"Flock controls","系统状态":"System status","训练状态":"Training status","学习状态":"Learning status","搜索状态":"Search status","群体状态":"Flock status",
  "启动系统":"Start system","暂停系统":"Pause system","开始训练":"Start training","暂停训练":"Pause training","开始学习":"Start learning","暂停学习":"Pause learning","开始搜索":"Start search","暂停搜索":"Pause search","启动群体":"Start flock","暂停群体":"Pause flock","开始演化":"Start evolution","暂停演化":"Pause evolution",
  "单步调度":"Run one dispatch step","重置仓库":"Reset warehouse","单步训练":"Run one training step","重置网络":"Reset network","单步学习":"Run one learning step","重置Q表":"Reset Q table","单步搜索":"Run one search step","重置路线":"Reset route","单步群体":"Run one flock step","重置群体":"Reset flock",
  "多机器人\n协作搬运":"Multi-robot\ncoordination","机器人数量":"Robots","目标任务积压":"Target backlog","调度速度":"Dispatch speed","调度规则":"Dispatch rules","最近空闲机器人优先":"Nearest idle robot first","等待时间决定动态路权":"Waiting time sets dynamic priority","迎面相遇时低优先级者主动侧让":"Lower-priority robot yields in head-on traffic","三步未动即驶入临时避让格":"After three blocked steps, move into a temporary yielding cell",
  "动态仓库地图":"Dynamic warehouse map","图例":"Legend","机器人":"Robot","待取货物":"Waiting cargo","卸货区":"Drop zone","当前规划路径":"Current planned route","已完成":"Completed","件货物":"items","系统利用率":"Utilization","等待任务":"Waiting tasks","尚未分配":"unassigned","避免冲突":"Conflicts avoided","次停车":"stops","累计完成量":"Cumulative completion","机器人队列":"Robot queue","空闲":"Idle","前往取货":"Heading to pickup","正在配送":"Delivering","系统提示":"System note","点击地图中的机器人查看个体状态。增加机器人不一定提高效率：狭窄通道会产生更多路径冲突。":"Select a robot on the map to inspect it. More robots do not always improve throughput because narrow aisles create more conflicts.",
  "神经网络\n如何学会分类":"How a neural network\nlearns to classify","隐藏神经元":"Hidden neurons","学习率 η":"Learning rate η","训练速度":"Training speed","激活函数":"Activation","点击画布添加样本":"Click the canvas to add samples","类别 A":"Class A","类别 B":"Class B","重建数据集":"Regenerate dataset","决策边界训练场":"Decision-boundary training field","背景颜色 = 网络预测概率":"Background color = predicted probability","交叉熵损失":"Cross-entropy loss","训练准确率":"Training accuracy","训练轮数":"Epochs","样本数量":"Samples","损失变化":"Loss over time","网络结构":"Network architecture","损失下降表示预测概率更接近标签；准确率不变时，损失仍可能继续改善。":"Lower loss means predicted probabilities better match the labels. Loss can still improve even when accuracy is unchanged.",
  "智能体如何\n试错走出迷宫":"How an agent\nescapes by trial and error","学习率 α":"Learning rate α","折扣因子 γ":"Discount factor γ","探索率 ε":"Exploration rate ε","运行速度":"Run speed","奖励规则":"Reward rules","终点 +20":"Goal +20","陷阱 −15":"Trap -15","撞墙 −1":"Wall -1","普通移动 −0.2":"Move -0.2","Q 值迷宫":"Q-value maze","智能体":"Agent","箭头 = 当前最佳动作":"Arrow = current best action","绿色越深 = 状态价值越高":"Darker green = higher state value","完成回合":"Episodes","当前回报":"Current return","当前步数":"Current steps","近20轮成功率":"Success rate, last 20","每回合累计回报":"Return per episode","最近一次更新":"Latest update",
  "旅行商问题\n路线优化":"Traveling salesman\nroute optimization","搜索算法":"Search algorithm","遗传搜索":"Genetic search","模拟退火":"Simulated annealing","城市数量":"Cities","搜索速度":"Search speed","生成另一组城市 ↻":"Generate new cities ↻","候选路线空间":"Candidate route space","当前最佳":"Current best","初始最近邻路线":"Initial nearest-neighbor route","所有路线均回到起点":"Every route returns to the start","当前最佳路程":"Best distance","距离单位":"distance units","相对基线改进":"Improvement over baseline","迭代次数":"Iterations","理论搜索空间":"Theoretical search space","当前温度":"Temperature","最佳距离收敛":"Best-distance convergence","当前观察":"Current observation",
  "简单规则如何\n形成群体智能":"How simple rules\ncreate swarm intelligence","个体数量":"Agents","分离权重":"Separation weight","对齐权重":"Alignment weight","聚合权重":"Cohesion weight","感知半径":"Perception radius","移动速度":"Movement speed","关闭捕食者":"Remove predator","加入捕食者":"Add predator","涌现行为场":"Emergent behavior field","个体":"Agent","R1 的感知半径":"R1 perception radius","点击场地可移动捕食者":"Click the field to move the predator","方向一致度":"Direction alignment","平均邻居数":"Mean neighbors","平均速度":"Mean speed","当前个体":"Current agents","方向一致度变化":"Direction alignment over time","本步平均规则强度":"Mean rule force this step","分离":"Separation","对齐":"Alignment","聚合":"Cohesion","避障":"Avoidance","黄色个体只用于增强空间辨识，遵循与绿色个体完全相同的规则。":"Yellow agents improve spatial readability and follow exactly the same rules as green agents.",
  "策略图例":"Strategy legend","个体交互场":"Interaction field","种群状态":"Population status","总结本轮":"Summarize run","存活个体":"Surviving agents","合作率":"Cooperation rate","平均收益":"Mean payoff","本代净变化":"Net change","种群大小":"Population size","合作行为比例":"Share of cooperative actions","策略表型分布":"Strategy phenotype distribution","按最近原型归类":"Classified by nearest prototype","点击一个个体查看基因":"Select an agent to inspect its genome","随机配对":"Random pairing","重复博弈":"Repeated game","收益适应度":"Payoff fitness","选择 · 交叉 · 突变":"Selection, crossover, mutation","经典框架，\n透明扩展。":"Classic framework,\ntransparent extensions.",
  "一步状态转移":"One state transition","一次状态转移":"One state transition","每一代的演化循环":"Evolution cycle per generation","一次训练循环":"One training cycle","每个个体的局部循环":"Local cycle for each agent","中央调度的三层决策":"Three layers of dispatch decisions","核心代价与优先级":"Cost and priority","核心计算":"Core calculation","时序差分更新":"Temporal-difference update","局部规则的合成":"Combining local rules"
  ,"Axelrod-Python 文档":"Axelrod-Python documentation","开源项目":"Open-source project","以牙还牙":"Tit for Tat","永远合作":"Always Cooperate","永远背叛":"Always Defect","赢留输变":"Win-Stay Lose-Shift","混合策略":"Mixed strategy","实验已就绪 · 等待开始":"Experiment ready. Waiting to start","对方 C":"Opponent C","对方 D":"Opponent D","自己 C":"Self C","自己 D":"Self D","承载量":"Capacity","C / 全部行动":"C / all actions","基因不是固定标签，而是五个合作概率：第一次行动，以及上一轮四种结果后的下一步选择。表型名称只是与经典策略原型的最近距离。":"A genome contains five cooperation probabilities: the first move and the response after each previous outcome. The phenotype is the nearest classic strategy prototype.","初次":"Initial","CC 后":"After CC","CD 后":"After CD","DC 后":"After DC","DD 后":"After DD","示例配对 等待首次配对":"Example pair: waiting for the first encounter","最后一轮行为：-　每轮平均收益：-":"Last-round actions: -   Mean payoff per round: -","全体合作率":"Overall cooperation","每人每轮":"per agent per round","出生":"Births","死亡":"Deaths","下一代种群":"Next population","C/D 标签显示双方最后一轮行动；适应度使用整次相遇的平均收益，而不是只看最后一轮。":"C/D labels show the final actions. Fitness uses the mean payoff across the full encounter, not only the last round.","经典框架，":"Classic framework,","透明扩展。":"transparent extensions.","网页借鉴 Axelrod-Python 的重复囚徒困境、策略竞赛与演化过程思想；没有直接复制其计算代码。为了让“种群大小”可变化，我们加入显式出生-死亡和环境承载量，而不是把固定种群的 Moran 过程伪装成数量增长。":"The experiment draws on Axelrod-Python's repeated games and evolutionary tournaments without copying its implementation. Explicit births, deaths, and carrying capacity allow population size to change.","策略基因":"Strategy genome","采用 memory-one 概率向量 p=(p₀,pCC,pCD,pDC,pDD)。交叉逐位继承双亲概率，突变加入小幅随机扰动。":"A memory-one probability vector p=(p₀,pCC,pCD,pDC,pDD) is inherited through crossover and perturbed by mutation.","自然选择":"Natural selection","重复博弈的每轮平均收益映射为繁殖权重。选择压力越高，收益差异对后代数量的放大越强。":"Mean payoff per round maps to reproductive weight. Stronger selection amplifies payoff differences.","生态数量":"Population ecology","出生率同时受平均收益和承载量 K 约束，死亡率包含基础死亡与超载惩罚。因此高合作可能支撑更大种群，但不保证任何策略必胜。":"Birth rate depends on payoff and carrying capacity K; death includes baseline and overload penalties. Cooperation may support a larger population but guarantees no winning strategy.","研究与成熟项目":"Research and mature projects","Axelrod-Python 文档 · 开源项目":"Axelrod-Python documentation · Open-source project",
  "等待首次调度":"Waiting for the first dispatch","新分配任务":"New assignments","最近空闲机器人":"nearest idle robot","重新规划":"Replanned","绕开当前车队":"avoid current fleet","成功移动":"Successful moves","预约被阻挡":"Reservations blocked","本步停车数":"stops this step","主动侧让":"Active yields","打破局部死锁":"break local deadlocks","先为每台机器人提出下一格，再按等待时间排序预约目的格；只有目的格唯一、且原占用者也能离开时，移动才会被批准。":"Each robot proposes a next cell. Reservations are prioritized by waiting time, and a move is approved only when the destination is unique and its current occupant can leave.","每当机器人空闲，调度器计算它到全部等待货物的曼哈顿距离，并选择最近目标。这个贪心规则响应快，但不保证全局最优。":"When a robot becomes idle, the dispatcher selects the waiting cargo with the shortest Manhattan distance. This greedy rule is fast but not globally optimal.","动态路权":"Dynamic right of way","等待时间越长，机器人下一步的预约优先级越高。这样不会由固定编号长期占据主通道，也能减少局部饥饿。":"Longer waits earn higher reservation priority, preventing fixed IDs from monopolizing an aisle and reducing starvation.","主动让行":"Active yielding","迎面交换或连续三步无法前进时，低路权机器人会驶入交通较少的相邻格，随后从新位置重新规划，主动打破局部死锁。":"During a head-on swap or after three blocked steps, the lower-priority robot moves to a quieter adjacent cell and replans from there.",
  "一组路线同时竞争；保留精英路线，通过有序交叉和交换突变产生下一代。":"Routes compete as a population. Elite routes survive while ordered crossover and swap mutation produce the next generation.","越低越好 · 显示最近 100 次":"Lower is better · Last 100 iterations","搜索刚开始，路线仍高度依赖初始解。":"The search has just begun and still depends strongly on its initial route.","等待首次搜索":"Waiting for the first search step","选择算法后点击单步，可逐次查看候选解。":"Choose an algorithm and step through its candidate solutions.","计算前距离":"Distance before","候选距离":"Candidate distance","距离变化 Δ":"Distance change Δ","是否刷新最优":"New best?","否":"No","是":"Yes","精英仍会保留":"Elites remain preserved","组合爆炸":"Combinatorial explosion","固定起点并忽略反向等价，一共有约 (n−1)!/2 条不同回路。50座城市的完整穷举在现实中不可行。":"With a fixed start and reverse-equivalent tours removed, about (n-1)!/2 routes remain. Exhaustive search over 50 cities is impractical.","遗传搜索和模拟退火允许暂时保留不完美答案，以换取跳出局部最优的机会；2-opt则专注稳定改进。":"Genetic search and simulated annealing may retain imperfect answers to escape local optima, while 2-opt focuses on steady improvement.","好解不等于最优解":"A good solution is not proof of optimality","曲线停止下降只说明算法暂时找不到更好路线。除非使用精确算法证明下界，否则不能声称已找到全局最优。":"A flat curve only means the algorithm has not found a better route. Without an exact lower-bound proof, it cannot claim the global optimum.",
  "2 输入":"2 inputs","6 隐藏":"6 hidden","1 输出":"1 output","平均梯度强度":"Mean gradient magnitude","最后样本预测":"Last-sample prediction",
  "利用：选择当前 Q 值最高的动作":"Exploit: choose the action with the highest current Q value","本步使用当前价值最高的动作。":"This step uses the action with the highest current value.","更新前 Q":"Q before","TD 目标":"TD target","更新后 Q":"Q after","当前回合":"Current episode","回合内步数":"Steps in episode","平均间距":"Mean spacing","平均邻居":"Mean neighbors","分离力":"Separation force","对齐力":"Alignment force","聚合力":"Cohesion force","避障/逃逸力":"Avoidance / escape force",
  " 忙碌":" busy"," 件":" items","车队累计移动 ":"Fleet distance: "," 格":" cells","第 ":"Generation "," 代":"","个体 #":"Agent #","示例配对 ":"Example pair: ","等待首次配对":"waiting for the first encounter","最后一轮行为：":"Last-round actions: ","每轮平均收益：":"Mean payoff per round: "," 隐藏":" hidden","累计执行 ":"Total steps: "," 步。达到终点、掉入陷阱或超过 120 步后开始新回合。":". A new episode begins after reaching the goal, hitting a trap, or exceeding 120 steps.","动作 ":"Action "," · 奖励 ":" · Reward ",
  "忙碌":"busy","件":"items","车队累计移动":"Fleet distance:","格":"cells","第":"Generation","代":"","示例配对":"Example pair:","最后一轮行为：":"Last-round actions:","每轮平均收益：":"Mean payoff per round:","隐藏":"hidden","累计执行":"Total steps:","步。达到终点、掉入陷阱或超过 120 步后开始新回合。":". A new episode begins after reaching the goal, hitting a trap, or exceeding 120 steps.","动作":"Action","· 奖励":"· Reward"
};

const Context=createContext<{language:Language;setLanguage:(v:Language)=>void;tr:(v:string)=>string}>({language:"zh",setLanguage:()=>{},tr:v=>v});

function translateString(value:string){
  const core=value.trim(),direct=dictionary[core]; if(direct!==undefined)return value.replace(core,direct);
  const transformed=core
    .replace(/^(\d+(?:\.\d+)?) 台$/,"$1 robots")
    .replace(/^(\d+(?:\.\d+)?) 个$/,"$1 agents")
    .replace(/^(\d+(?:\.\d+)?) 件$/,"$1 items")
    .replace(/^(\d+(?:\.\d+)?) 座$/,"$1 cities")
    .replace(/^(\d+(?:\.\d+)?) 轮$/,"$1 rounds")
    .replace(/^(\d+(?:\.\d+)?) 代\/秒$/,"$1 generations/s")
    .replace(/^(\d+(?:\.\d+)?) 步\/秒$/,"$1 steps/s")
    .replace(/^(\d+(?:\.\d+)?) 次\/秒$/,"$1 iterations/s")
    .replace(/^(\d+(?:\.\d+)?) 轮\/秒$/,"$1 epochs/s")
    .replace(/^第 (\d+) 代$/,"Generation $1")
    .replace(/^承载量 (\d+)$/,"Capacity $1")
    .replace(/^(\d+)\/(\d+) 忙碌$/,"$1/$2 busy")
    .replace(/^车队累计移动 (\d+) 格$/,"Fleet distance: $1 cells")
    .replace(/^共 (\d+) 台机器人$/,"$1 robots total")
    .replace(/^累计执行 (\d+) 步。达到终点、掉入陷阱或超过 120 步后开始新回合。$/,"$1 total steps. A new episode begins after reaching the goal, hitting a trap, or exceeding 120 steps.")
    .replace(/^动作 (.+) · 奖励 (.+)$/,"Action $1 · Reward $2")
    .replace(/^个体 #(\d+) · (.+)$/,"Agent #$1 · $2")
    .replace(/^承载量 K=(\d+)$/,"Capacity K=$1")
    .replaceAll("以牙还牙","Tit for Tat")
    .replaceAll("永远合作","Always Cooperate")
    .replaceAll("永远背叛","Always Defect")
    .replaceAll("赢留输变","Win-Stay Lose-Shift")
    .replaceAll("混合策略","Mixed strategy");
  return value.replace(core,transformed);
}

export function LanguageProvider({children}:{children:ReactNode}){
  const[language,setLanguage]=useState<Language>("zh");
  const[languageGate,setLanguageGate]=useState(true);
  useEffect(()=>{const saved=localStorage.getItem("algorithm-language");if(saved==="en")window.setTimeout(()=>setLanguage("en"),0);if(saved==="zh"||saved==="en")window.setTimeout(()=>setLanguageGate(false),0)},[]);
  useEffect(()=>{document.documentElement.lang=language==="zh"?"zh-CN":"en";document.documentElement.dataset.language=language;localStorage.setItem("algorithm-language",language);document.title=language==="zh"?"算法可视化实验室":"Algorithm Visualization Laboratory"},[language]);
  const value=useMemo(()=>({language,setLanguage,tr:(v:string)=>language==="en"?translateString(v):v}),[language]);
  const chooseLanguage=(next:Language)=>{setLanguage(next);localStorage.setItem("algorithm-language",next);setLanguageGate(false)};
  return <Context.Provider value={value}>{children}{languageGate&&<div className="language-gate" role="dialog" aria-modal="true" aria-labelledby="language-gate-title"><div className="language-gate-card"><span className="language-gate-mark">A / V</span><p className="language-gate-kicker">ALGORITHM VISUALIZATION LABORATORY</p><h1 id="language-gate-title">选择语言<br/><em>Choose a language</em></h1><p className="language-gate-note">选择后将记住你的偏好。</p><div className="language-gate-actions"><button onClick={()=>chooseLanguage("zh")}>中文<br/><small>简体中文</small></button><button onClick={()=>chooseLanguage("en")}>English<br/><small>Continue in English</small></button></div></div></div>}</Context.Provider>;
}

export const useLanguage=()=>useContext(Context);

export function LanguageToggle(){const{language,setLanguage}=useLanguage();return <div className="language-toggle" role="group" aria-label={language==="zh"?"语言选择":"Language selection"}><button className={language==="zh"?"active":""} onClick={()=>setLanguage("zh")} aria-pressed={language==="zh"}>中文</button><button className={language==="en"?"active":""} onClick={()=>setLanguage("en")} aria-pressed={language==="en"}>EN</button></div>}

const translatedPropKeys=new Set(["children","title","subtitle","label","note","effect","name","hint","display","value","steps","items","tabs","aria-label","placeholder"]);
function localizeValue(value:unknown,tr:(v:string)=>string):unknown{
  if(typeof value==="string")return tr(value);
  if(Array.isArray(value))return value.map((v,i)=>{const translated=localizeValue(v,tr);return isValidElement(translated)&&translated.key==null?cloneElement(translated,{key:`localized-${i}`}):translated});
  if(isValidElement(value))return localizeElement(value,tr);
  if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,translatedPropKeys.has(k)||["content","label","effect","name","hint"].includes(k)?localizeValue(v,tr):v]));
  return value;
}
function localizeElement(node:ReactElement,tr:(v:string)=>string):ReactElement{
  const props=node.props as Record<string,unknown>,next:Record<string,unknown>={};
  for(const[k,v]of Object.entries(props))next[k]=translatedPropKeys.has(k)?localizeValue(v,tr):v;
  return cloneElement(node,next);
}
export function Localized({children}:{children:ReactNode}){const{language,tr}=useLanguage();if(language==="zh")return <>{children}</>;return <>{Children.map(children,node=>isValidElement(node)?localizeElement(node,tr):typeof node==="string"?tr(node):node)}</>}
