"use client";

import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import Link from "next/link";
import AlgorithmWorkbench,{CalcGrid,Formula,HistoryScrubber,ParamList,ProcessFlow} from "./algorithm-workbench";
import {Localized} from "./language-provider";

type Point={x:number;y:number;label:0|1};
type Model={w1:number[][];b1:number[];w2:number[];b2:number};
type Snap={epoch:number;loss:number;accuracy:number};
type Activation="tanh"|"relu"|"sigmoid";
const seeded=(seed:number)=>()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
const makeModel=(h:number,random=Math.random):Model=>{const rand=()=>random()*2-1;return{w1:Array.from({length:h},()=>[rand()*.8,rand()*.8]),b1:Array(h).fill(0),w2:Array.from({length:h},()=>rand()*.7),b2:0}};
const activate=(z:number,a:Activation)=>a==="tanh"?Math.tanh(z):a==="relu"?Math.max(0,z):1/(1+Math.exp(-z));
const derivative=(z:number,v:number,a:Activation)=>a==="tanh"?1-v*v:a==="relu"?(z>0?1:0):v*(1-v);
const sigmoid=(z:number)=>1/(1+Math.exp(-Math.max(-20,Math.min(20,z))));
function predict(model:Model,p:Point|{x:number;y:number},activation:Activation){const x=[p.x/50-1,p.y/50-1],hidden=model.w1.map((w,i)=>activate(w[0]*x[0]+w[1]*x[1]+model.b1[i],activation));return sigmoid(hidden.reduce((s,v,i)=>s+v*model.w2[i],model.b2))}
function dataset(random=Math.random){const pts:Point[]=[];for(let i=0;i<34;i++){const a=i/34*Math.PI*2,r=14+random()*5;pts.push({x:32+Math.cos(a)*r+(random()-.5)*6,y:48+Math.sin(a)*r*.65+(random()-.5)*5,label:0});pts.push({x:68+Math.cos(a)*r+(random()-.5)*6,y:52+Math.sin(a)*r*.65+(random()-.5)*5,label:1})}return pts}
function LossChart({data}:{data:Snap[]}){const d=data.slice(-100),max=Math.max(.1,...d.map(x=>x.loss));const pts=d.map((x,i)=>`${i/Math.max(1,d.length-1)*100},${4+x.loss/max*48}`).join(" ");return <svg viewBox="0 0 100 56" preserveAspectRatio="none" className="ai-mini-chart"><path d="M0 4H100M0 28H100M0 52H100"/><polyline points={pts}/></svg>}

export default function NeuralLab(){
  const[hidden,setHidden]=useState(6),[learningRate,setLearningRate]=useState(.12),[activation,setActivation]=useState<Activation>("tanh"),[speed,setSpeed]=useState(160),[running,setRunning]=useState(false),[drawLabel,setDrawLabel]=useState<0|1>(0);
  const[points,setPoints]=useState<Point[]>(()=>dataset(seeded(23))),[model,setModel]=useState<Model>(()=>makeModel(6,seeded(71))),[epoch,setEpoch]=useState(0),[history,setHistory]=useState<Snap[]>([{epoch:0,loss:.693,accuracy:50}]),[trace,setTrace]=useState({loss:.693,accuracy:50,gradient:0,prediction:.5});
  const[replayIndex,setReplayIndex]=useState(0);const modelRef=useRef(model),epochRef=useRef(epoch),pointsRef=useRef(points);
  useEffect(()=>{modelRef.current=model},[model]);useEffect(()=>{epochRef.current=epoch},[epoch]);useEffect(()=>{pointsRef.current=points},[points]);
  const reset=useCallback((h=hidden)=>{const m=makeModel(h);setRunning(false);setModel(m);setEpoch(0);setHistory([{epoch:0,loss:.693,accuracy:50}]);setReplayIndex(0);setTrace({loss:.693,accuracy:50,gradient:0,prediction:.5})},[hidden]);
  const train=useCallback(()=>{const m=modelRef.current,pts=pointsRef.current;if(!pts.length)return;const gw1=m.w1.map(()=>[0,0]),gb1=m.b1.map(()=>0),gw2=m.w2.map(()=>0);let gb2=0,loss=0,correct=0,lastPred=.5;
    for(const p of pts){const x=[p.x/50-1,p.y/50-1],z=m.w1.map((w,i)=>w[0]*x[0]+w[1]*x[1]+m.b1[i]),a=z.map(v=>activate(v,activation)),out=sigmoid(a.reduce((s,v,i)=>s+v*m.w2[i],m.b2));lastPred=out;loss+=-(p.label*Math.log(out+1e-8)+(1-p.label)*Math.log(1-out+1e-8));if((out>=.5?1:0)===p.label)correct++;const dz=out-p.label;gb2+=dz;for(let j=0;j<m.w2.length;j++){gw2[j]+=dz*a[j];const dh=dz*m.w2[j]*derivative(z[j],a[j],activation);gw1[j][0]+=dh*x[0];gw1[j][1]+=dh*x[1];gb1[j]+=dh}}
    const n=pts.length,nm:Model={w1:m.w1.map((w,j)=>w.map((v,k)=>v-learningRate*gw1[j][k]/n)),b1:m.b1.map((v,j)=>v-learningRate*gb1[j]/n),w2:m.w2.map((v,j)=>v-learningRate*gw2[j]/n),b2:m.b2-learningRate*gb2/n};const e=epochRef.current+1,s={epoch:e,loss:loss/n,accuracy:correct/n*100},g=(gw2.reduce((a,b)=>a+Math.abs(b),0)+gw1.flat().reduce((a,b)=>a+Math.abs(b),0))/n;setModel(nm);setEpoch(e);setTrace({...s,gradient:g,prediction:lastPred});setHistory(h=>{const next=[...h,s];setReplayIndex(next.length-1);return next})
  },[activation,learningRate]);
  useEffect(()=>{if(!running)return;const t=window.setInterval(train,speed);return()=>window.clearInterval(t)},[running,speed,train]);
  const latest=history.at(-1)!,replay=history[Math.min(replayIndex,history.length-1)]??latest;
  const grid=useMemo(()=>Array.from({length:20*14},(_,i)=>{const x=i%20,y=Math.floor(i/20),p=predict(model,{x:(x+.5)*5,y:(y+.5)*(100/14)},activation);return{x,y,p}}),[model,activation]);
  return <Localized><main className="viz-page ai-page neural-page"><header className="viz-nav"><Link href="/" className="exit-lab viz-exit"><span className="exit-symbol">←</span><span><b>退出实验</b><small>返回目录</small></span></Link><span>04 / SUPERVISED LEARNING</span><Link href="/q-learning" className="next-lab">下一个实验 →</Link></header>
    <section className="viz-intro"><div><p className="viz-kicker">Neural network laboratory</p><h1>神经网络<br/>如何学会分类</h1></div><p>网络从随机权重开始。每轮训练都先预测，再沿误差反向计算梯度，让决策边界逐渐贴合你在画布上放置的数据。</p></section>
    <section className="ai-workspace"><aside className="viz-controls"><div className="viz-panel-title">训练控制 <small>CONTROL</small></div><div className="viz-run"><button onClick={()=>setRunning(v=>!v)}>{running?"暂停训练":"开始训练"}</button><button onClick={train} aria-label="单步训练">+1</button><button onClick={()=>reset()} aria-label="重置网络">↻</button></div>
      <AiRange label="隐藏神经元" value={hidden} min={2} max={12} step={1} display={`${hidden} 个`} onChange={v=>{setHidden(v);reset(v)}}/><AiRange label="学习率 η" value={learningRate} min={.01} max={.5} step={.01} display={learningRate.toFixed(2)} onChange={setLearningRate}/><AiRange label="训练速度" value={speed} min={40} max={600} step={20} display={`${(1000/speed).toFixed(1)} 轮/秒`} onChange={setSpeed} reverse/>
      <div className="ai-select"><label>激活函数</label><select value={activation} onChange={e=>{setActivation(e.target.value as Activation);reset()}}><option value="tanh">Tanh</option><option value="relu">ReLU</option><option value="sigmoid">Sigmoid</option></select></div><div className="draw-tools"><label>点击画布添加样本</label><button className={drawLabel===0?"active blue":""} onClick={()=>setDrawLabel(0)}>类别 A</button><button className={drawLabel===1?"active red":""} onClick={()=>setDrawLabel(1)}>类别 B</button><button onClick={()=>{setPoints(dataset());reset()}}>重建数据集</button></div>
    </aside><section className="ai-stage"><div className="warehouse-head"><span>决策边界训练场</span><div><i className={running?"on":""}/>{running?"TRAINING":"PAUSED"} · EPOCH {epoch}</div></div><svg viewBox="0 0 100 100" className="decision-map" aria-label="神经网络决策边界" onClick={e=>{const r=e.currentTarget.getBoundingClientRect();setPoints(p=>[...p,{x:(e.clientX-r.left)/r.width*100,y:(e.clientY-r.top)/r.height*100,label:drawLabel}])}}>{grid.map(c=><rect key={`${c.x}-${c.y}`} x={c.x*5} y={c.y*(100/14)} width="5.2" height={100/14+.2} fill={c.p>.5?`rgba(189,91,76,${.07+Math.abs(c.p-.5)*.42})`:`rgba(87,124,154,${.07+Math.abs(c.p-.5)*.42})`}/>)}<path d="M50 0V100M0 50H100" className="axis-cross"/>{points.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="1.4" className={p.label?"class-b":"class-a"}/>)}</svg><div className="ai-legend"><span><i className="legend-a"/>类别 A</span><span><i className="legend-b"/>类别 B</span><span>背景颜色 = 网络预测概率</span></div></section>
      <aside className="ai-stats"><div className="viz-panel-title">训练状态 <small>LIVE METRICS</small></div><div className="ai-kpis"><div><span>交叉熵损失</span><b>{latest.loss.toFixed(3)}</b></div><div><span>训练准确率</span><b>{latest.accuracy.toFixed(1)}%</b></div><div><span>训练轮数</span><b>{epoch}</b></div><div><span>样本数量</span><b>{points.length}</b></div></div><div className="ai-chart"><span>损失变化</span><LossChart data={history}/></div><div className="network-mini"><span>网络结构</span><div className="network-layout"><div><i/><i/><small>2 输入</small></div><b>→</b><div className="hidden-stack">{Array.from({length:hidden},(_,i)=><i key={i}/>) }<small>{hidden} 隐藏</small></div><b>→</b><div><i className="output-node"/><small>1 输出</small></div></div></div><p className="ai-note">损失下降表示预测概率更接近标签；准确率不变时，损失仍可能继续改善。</p></aside></section>
    <AlgorithmWorkbench title="权重是怎样沿误差方向更新的" subtitle="观察一次完整的前向预测、损失计算、梯度回传与参数更新。" tabs={[
      {id:"principle",label:"算法原理",content:<div className="workbench-split"><div><h3>一次训练循环</h3><ProcessFlow steps={["输入二维样本","隐藏层计算激活","输出分类概率","计算交叉熵误差","反向传播并更新权重"]}/></div><div><h3>核心计算</h3><Formula note="隐藏层把二维输入投影到多个可学习特征。">h = φ(W₁x + b₁)</Formula><Formula note="学习率 η 决定每次沿负梯度方向移动多远。">W ← W − η∇L</Formula></div></div>},
      {id:"step",label:"本轮计算",content:<CalcGrid items={[{label:"训练轮数",value:epoch},{label:"交叉熵损失",value:trace.loss.toFixed(4),tone:trace.loss<.3?"good":undefined},{label:"训练准确率",value:`${trace.accuracy.toFixed(1)}%`},{label:"平均梯度强度",value:trace.gradient.toFixed(3)},{label:"最后样本预测",value:`${(trace.prediction*100).toFixed(1)}%`} ]}/>},
      {id:"history",label:"历史回放",content:<HistoryScrubber value={replayIndex} max={history.length-1} onChange={setReplayIndex} label={`EPOCH ${replay.epoch}`}><CalcGrid items={[{label:"当时损失",value:replay.loss.toFixed(4)},{label:"当时准确率",value:`${replay.accuracy.toFixed(1)}%`},{label:"较初始损失",value:`${(replay.loss-history[0].loss).toFixed(3)}`}]}/></HistoryScrubber>},
      {id:"parameters",label:"参数解释",content:<ParamList items={[{symbol:"H",name:"隐藏神经元",effect:"增加表达能力，也可能让边界更复杂并提高过拟合风险。"},{symbol:"η",name:"学习率",effect:"太小收敛慢，太大可能在最优点附近震荡甚至发散。"},{symbol:"φ",name:"激活函数",effect:"引入非线性；没有它，多层网络仍只能学习线性边界。"},{symbol:"N",name:"训练样本",effect:"点击画布可增加样本，直接改变损失函数和最终边界。"}]}/>} ]}/>
  </main></Localized>
}
function AiRange({label,value,min,max,step,display,onChange,reverse=false}:{label:string;value:number;min:number;max:number;step:number;display:string;onChange:(n:number)=>void;reverse?:boolean}){return <div className="viz-control"><label>{label}<b>{display}</b></label><input aria-label={label} type="range" value={value} min={min} max={max} step={step} onChange={e=>onChange(+e.target.value)} style={reverse?{direction:"rtl"}:undefined}/><small><span>{min}</span><span>{max}</span></small></div>}
